### ISSUE TITLE
error when running script

### ISSUE THREAD

**Issue by chisan0501** [HaroldMitts/wininstall#6]
https://github.com/HaroldMitts/wininstall/blob/8f6ccc91a9c6eb51d790808731a405ba54a33136/wininstall.cmd#L35

seems like you will need to add
wpeutil UpdateBootInfo below line 35
else the script will throw an error

**Comment by HaroldMitts** [comment]
Thanks Chisan, it does not return the error for me, but I saw the error Charles sent me, so I don't see any harm to add the command, especially if it resolves your error.

Can you please confirm if adding the command resolves the error?

**Comment by chisan0501** [comment]
Harold, I can confirm adding wpeutil UpdateBootInfo below line 35 would resolve the error.

**Comment by HaroldMitts** [comment]
Great, I am glad it worked out. Thank you for letting me know. I have added the command to line 36.
